sudo: required
services:
  - docker

script:
  - GH=mh-cbon/gh-api-cli sh -xe aptly.sh 
  - ls -alh
  - ls -alh apt
  - ls -alh apt/*
  - ls -alh apt/*/*/*/*

env:
  global:
    - secure: >-
        dttbeFVlNd2Hv9qjBIRt97WTVwQxNu+1Oyko9uOEJDX1vn2m7UZh850xwBVnKU5VewrRtfEHfBGRMxXjfIamHUkv5F5zZq2na6PNBCOJmlQ5vSaUWSxsD5605VKyb4sfC5GMTX2l/3SZeSGOhDljos4XGZRVptbPgu4p5VVWCJ0Soot1cu1XJQfXCHNn9IKZyibZMZWqQAJVfFfESYO2nsUojSbODj95C4uq8/DRcPv91fA3wyJ82/azBrnjufjXFI2db1YmmGfbQvQKkE8MEYxibssOZ3BP0RiKdgf/P2dqLorYSh+WXd/tethtyJjSb0GwB+OidSFKMxLna7OWNWaMExeHq+uhJYNxv4D6avniJ1n45y9BPMFN+Wp8YZZp1GZvXlCYKDrBU4wO9mNHmBUvQx6/yAsgyhwowt/aucj80/OIffKXsScaSy36v+64M/b9l5td0hBIVtW6n0oHicie0gWNgzzHPazfcR+JEkuFYhbCUT8/OJvsQcItJG++qoO0MUo9Vx14WWvRkWq/UdGHTLlWgq3raouCvmgJRGwsrSQKtIEhw6huVlLJjkNnruDA4AZpLeH7erjX/bMOVN1XeoT98//RNBtU33sVi0incRM/u36YQ7EiIzB/KjRzVV00WVSoCRD/rkbIKl5SLfV3bCXzdo1vlcn5qm+XTWA=
